version: '3'
services:
  orchestrator:
    image: "aspnetapp"
    restart: on-failure
    depends_on:
      - "rabbit"
    ports:
      - "5000:80"
    # networks:
    #   - localnet
  consumer:
    image: "consumerapp"
    restart: on-failure
    depends_on:
      - "rabbit"
  rabbit:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    ports:
      - "15673:15672"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:5672"]
        interval: 30s
        timeout: 10s
        retries: 5
    # networks:
    #   - localnet
# networks:
#   localnet:
#     external:
#       name: localnet