version: '3.7'
services:
  orchestrator:
    image: "orchestrator:latest"
    restart: on-failure
    depends_on:
      - "gateway"
    ports:
      - "5001:80"
  card:
    image: "card:latest"
    restart: on-failure
    deploy:
      replicas: 3
    depends_on:
      - "gateway"
    ports:
      - "5002:80"
  gateway:
    image: "gateway:latest"
    ports:
      - "5000:80"
  # rabbit:
  #   image: "rabbitmq:3-management"
  #   hostname: "rabbit"
  #   ports:
  #     - "15673:15672"
  #   healthcheck:
  #       test: ["CMD", "curl", "-f", "http://localhost:5672"]
  #       interval: 30s
  #       timeout: 10s
  #       retries: 5